baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"

title = "seth.nz social links"
copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = false
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "@setheon"
   headline = "Photographer & Film Student based in Wellington, New Zealand."
   image = "img/author.png"  # path relative to static directory

  links = [
     { email = "mailto:info@seth.nz" },
     { link = "https://seth.nz/" },
     { instagram  = "https://instagram.com/fujiseth" },
     { linkedin = "https://www.linkedin.com/in/seth-copeland-524b50246/" },
     { youtube = "https://www.youtube.com/@setheon" },
    #{ mastodon = "https://mastodon.instance/@setheon" },
    #{ github = "https://github.com/setheon" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
